options:
  size: 2x # Double resources available for this step.

pipelines:
  branches:     # 'branches' section
    develop*:   # commits on develop branch will build and push the "test" tag
       - step:
          caches:
            - maven
            - docker
          script:
            - export $AWS_ACCESS_KEY_ID
            - export $AWS_SECRET_KEY
            - docker login --username="$DOCKER_USER" --password="$DOCKER_PWD"
            - docker build -t sono.tullio/palestra-in-cloud-api:test --build-arg palestra-in-cloud-api_environment=test .
            - docker push sono.tullio/palestra-in-cloud-api:test
          services:
            - docker
#  tags:         # 'tags' section
#    pre*:   # creation of a pre* tag will build and push the "preprod" tag
#       - step:
#          caches:
#            - maven
#            - docker
#          script:
#            - export $AWS_ACCESS_KEY_ID
#            - export $AWS_SECRET_KEY
#            - docker login --username="$DOCKER_USER" --password="$DOCKER_PWD"
#            - docker build -t holding14/swarm-api:pre --build-arg swarm_environment=pre .
#            - docker push holding14/swarm-api:pre
#          services:
#            - docker
#    rc*:        # creation of a rc* tag will build and push the tag itself (for storage purpouse)
#       - step:
#          caches:
#            - maven
#            - docker
#          script:
#            - export $AWS_ACCESS_KEY_ID
#            - export $AWS_SECRET_KEY
#            - docker login --username="$DOCKER_USER" --password="$DOCKER_PWD"
#            - docker build -t holding14/swarm-api:$BITBUCKET_TAG --build-arg swarm_environment=pre .
#            - docker push holding14/swarm-api:$BITBUCKET_TAG
#          services:
#            - docker
#    rel*:       # creation of a rel* tag will build and push the tag itself AND latest
#       - step:
#          caches:
#            - maven
#            - docker
#          script:
#            - export $AWS_ACCESS_KEY_ID
#            - export $AWS_SECRET_KEY
#            - docker login --username="$DOCKER_USER" --password="$DOCKER_PWD"
#            - docker build -t holding14/swarm-api:$BITBUCKET_TAG --build-arg swarm_environment=prod .
#            - docker tag holding14/swarm-api:$BITBUCKET_TAG holding14/swarm-api:latest
#            - docker push holding14/swarm-api:$BITBUCKET_TAG
#            - docker push holding14/swarm-api:latest
#          services:
#            - docker

definitions:
  services:
    docker:
      memory: 7128 #seems the maximum allowed for 2x builds
